Labs/01-web/110124/Models/Category/CategoryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _110124.Models.Product;

namespace _110124.Models.Category
{
    public class CategoryModel
    {
        public CategoryModel(string id, string name, ICollection<ProductModel> products)
        {
            Id = id;
            Name = name;
            Products = products;
        }

        public string Id { get; set; }
        public string Name { get; set; }
        public ICollection<ProductModel> Products { get; set; }
    }
}

Labs/01-web/110124/Models/Category/GetAllCategoryModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace _110124.Models.Category
{
    public class GetAllCategoryModel
    {
        public GetAllCategoryModel(string id, string name)
        {
            Id = id;
            Name = name;
        }

        [Required]
        public string Id { get; init; }

        [Required]
        public string Name { get; init; }
    }
}

Labs/01-web/110124/Models/ErrorViewModel.cs
namespace _110124.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Labs/01-web/110124/Models/Product/CreateProductModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _110124.Models.Product
{
    public class CreateProductModel
    {
        public CreateProductModel()
        {

        }
        public CreateProductModel(string name, string description, string imageUrl, decimal price, int quantity, string categoryId)
        {
            Name = name;
            Description = description;
            ImageUrl = imageUrl;
            Price = price;
            Quantity = quantity;
            CategoryId = categoryId;
        }


        public string Name { get; init; }

        public string Description { get; init; }

        public string ImageUrl { get; init; }

        public decimal Price { get; init; }

        public int Quantity { get; init; }
        public string CategoryId { get; set; }

    }
}

Labs/01-web/110124/Models/Product/GetAllProductsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _110124.Models.Product
{
    public class GetAllProductsModel
    {
        public GetAllProductsModel(string id, string name, string imageUrl, decimal price)
        {
            Id = id;
            Name = name;
            ImageUrl = imageUrl;
            Price = price;
        }

        public string Id { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
        public decimal Price { get; set; }

    }
}

Labs/01-web/110124/Models/Product/ProductModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _110124.Models.Product
{
    public class ProductModel
    {
        public ProductModel(string id, string name, string description, string imageUrl, decimal price, int quantity)
        {
            Id = id;
            Name = name;
            Description = description;
            ImageUrl = imageUrl;
            Price = price;
            Quantity = quantity;
        }

        public string Id { get; init; }

        public string Name { get; init; }

        public string Description { get; init; }

        public string ImageUrl { get; init; }

        public decimal Price { get; init; }

        public int Quantity { get; init; }
    }
}

Labs/01-web/110124/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using _110124.Data;
using _110124.Data.Entities;
using _110124.Models.Category;
using _110124.Models.Product;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace _110124.Controllers
{
    [Route("[controller]")]
    public class CategoriesController : Controller
    {
        private readonly ILogger<CategoriesController> _logger;
        private readonly AppDbContext _context;

        public CategoriesController(ILogger<CategoriesController> logger, AppDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        [HttpGet("")]
        [HttpGet("Index")]
        public async Task<IActionResult> Index()
        {
            IEnumerable<Category> categories = await _context.Categories.ToListAsync();
            IEnumerable<GetAllCategoryModel> categoryModels = categories.Select(c => new GetAllCategoryModel(c.Id, c.Name));
            return View(categoryModels);
        }
        [HttpGet("{id}")]
        [HttpGet("Index/{id}")]

        public async Task<IActionResult> GetById(string id)
        {
            Category category = await _context.Categories.FirstOrDefaultAsync(c => c.Id == id);
            if (category == null)
            {
                return NotFound();
            }
            ICollection<Product> products = await _context.Products.Where(p => p.CategoryId == id).ToListAsync();
            ICollection<ProductModel> productModels = products.Select(p => new ProductModel(p.Id, p.Name, p.Description, p.ImageUrl, p.Price, p.Quantity)).ToList();

            return View(new CategoryModel(category.Id, category.Name, productModels));
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Labs/01-web/110124/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using _110124.Models;

namespace _110124.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Labs/01-web/110124/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using _110124.Data;
using _110124.Data.Entities;
using _110124.Models.Product;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;

namespace _110124.Controllers
{
    [Route("[controller]")]
    public class ProductsController : Controller
    {
        private readonly ILogger<ProductsController> _logger;
        private readonly AppDbContext _context;

        public ProductsController(ILogger<ProductsController> logger, AppDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        [HttpGet("")]
        [HttpGet("Index")]
        public IActionResult Index()
        {
            ICollection<Product> products = _context.Products.ToList();
            IEnumerable<GetAllProductsModel> model = products.Select(p => new GetAllProductsModel(p.Id, p.Name, p.ImageUrl, p.Price));

            return View(model);
        }

        public IActionResult GetById(string id)
        {
            return View();
        }

        [HttpGet("Create")]
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");

            return View();
        }

        [HttpPost("Create")]
        public IActionResult Create(CreateProductModel model)
        {
            Product product = new Product();
            product.Name = model.Name;
            product.Description = model.Description;
            product.ImageUrl = model.ImageUrl;
            product.Price = model.Price;
            product.Quantity = model.Quantity;
            product.CategoryId = model.CategoryId;

            _context.Products.Add(product);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Labs/01-web/110124/Views/Categories/GetById.cshtml
@using _110124.Models.Category
@model CategoryModel

<section class="products">
    @if (Model != null)
    {
        <h3>Products in @Model.Name</h3>
        @if (Model.Products.Count > 0)
        {
            <h2>@Model.Name</h2>
            <ul>
                @foreach (var product in Model.Products)
                {
                    <li>
                        <a href="@Url.Action("Details", "Product", new { id = product.Id })">
                            <img src="@product.ImageUrl" alt="@product.Name" />
                            <h3>@product.Name</h3>
                            <p>@product.Description</p>
                        </a>
                    </li>
                }
            </ul>
        }
        else
        {
            <h2>No products found</h2>
        }
    }
</section>

Labs/01-web/110124/Views/Categories/Index.cshtml
@using _110124.Models.Category
@model IEnumerable<GetAllCategoryModel>

<section class="categories">
    @if (Model != null && Model.Count() > 0)
    {
        foreach (var item in Model.ToList())
        {
            <div class="category">
                <a class="nav-link text-dark" asp-controller="Categories" asp-action="" asp-route-id="@item.Id">@item.Name</a>
            </div>
        }
    }
    else
    {
        <h3>No categories found</h3>
    }

</section>

Labs/01-web/110124/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Labs/01-web/110124/Views/Products/Create.cshtml
@using _110124.Models.Product
@model CreateProductModel

<section class="create-product">
    <h2>Create Product</h2>
    <form asp-action="Create" method="post">
        <div class="form-group">
            <label asp-for="CategoryId" class="control-label">Category</label>
            <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
        </div>
        <div class="form-group>
            <label asp-for=" Name">Name</label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group>
            <label asp-for=" Price">Price</label>
            <input asp-for="Price" class="form-control" />
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>
        <div class="form-group>
            <label asp-for=" Quantity">Quantity</label>
            <input asp-for="Quantity" class="form-control" type="number" />
            <span asp-validation-for="Quantity" class="text-danger"></span>
        </div>

        <div class="form-group>
            <label asp-for=" Description">Description</label>
            <input asp-for="Description" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>

        <div class="form-group>
            <label asp-for=" ImageUrl">Image URL</label>
            <input asp-for="ImageUrl" class="form-control" />
            <span asp-validation-for="ImageUrl" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary mt-2">Create</button>
    </form>
</section>

Labs/01-web/110124/Views/Products/Index.cshtml
@using _110124.Models.Product
@model IEnumerable<GetAllProductsModel>

<section class="products">
    <h1>Products</h1>
    <a class="create-btn" asp-controller="Products" asp-action="Create"
        style="padding-left: 1rem; padding-right: 1rem; background-color:rgb(53, 238, 53); color: #ffffff; border-radius: 1rem;     text-decoration: none;">Create</a>

    @if (Model != null && Model.Count() > 0)
    {
        foreach (var item in Model.ToList())
        {
            <div class="category">
                <a class="nav-link text-dark" asp-controller="Products" asp-action="" asp-route-id="@item.Id">@item.Name</a>
            </div>
        }
    }
    else
    {
        <h3>No products found</h3>
    }

</section>

Labs/01-web/110124/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shop All in One</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/_110124.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Shop All in One</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Categories" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Products" asp-action="Index">Products</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - _110124 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>